### ISSUE TITLE
bug(convert_all): won't convert following unit's on one line if there are multiple

### ISSUE THREAD

**Issue by cjodo** [cjodo/convert.nvim#16]
issue happens when there are more than one value on one line, for example:

```css
selector {
    padding: 1px 1px 1px 1px;
}
```
Bug: convert all will only convert the first value
```css
selector {
    padding: 0.0625rem 1px 1px 1px;
}
```
